version: '2'

services:
  digital_twin:
    build: ./digital_twin
    environment:
      - MQTT_SERVER_ADDRESS=34.159.61.163
      - MQTT_1_SERVER_PORT=1883
      - MQTT_2_SERVER_PORT=1884
      - MQTT_USERNAME=dso_server
      - MQTT_PASSWORD=dso_password
      - NUMBER_RPIES=1  # number of physical RPies connected
      - PYTHONBUFFERED=1  # allows for the Python output to go directly to the shell
    volumes:
      - ./digital_twin/app:/etc/usr/src/app

  # digital_raspberry:
  #   build: ./digital_raspberry
  #   environment:
  #     - MQTT_SERVER_ADDRESS=34.159.252.9
  #     - MQTT_SERVER_PORT=1884
  #     - MQTT_USERNAME=dso_server
  #     - MQTT_PASSWORD=dso_password
  #     - PYTHONBUFFERED=1
  #   volumes:
  #     - ./digital_raspberry/app:/etc/usr/src/app
